# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    recipients:
      -roman.sercent@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    
env:
  global:
    - CODECOV_TOKEN="5491fb2e-7961-4282-ae7d-54514bad3880"    