insert into item_user (name) values ('Admin');
insert into item_user (name) values ('User');
insert into item_user (name) values ('User2');
insert into item_user (name) values ('User3');
insert into role (name, permissions) values ('admin_role', 10);
insert into role (name, permissions) values ('user_role', 1);
insert into rules (name, write, read, creating, delete) values ('admin_rule', true, true, true, true);
insert into rules (name, write, read, creating, delete) values ('user_rule', false, true, true, false);
insert into rules_role (name, role_id, rules_id) values ('admin_role_to_admin_rule', 1, 1);
insert into rules_role (name, role_id, rules_id) values ('user_role_to_user_role', 2, 2);
update item_user set role_id=1 where name='Admin';
update item_user set role_id=2 where name='User';
update item_user set role_id=2 where name='User2';
update item_user set role_id=2 where name='User3';
insert into category (name) values ('stuped users');
insert into category (name) values ('network');
insert into category (name) values ('OMG, what to do');
insert into state (status) values ('finish');
insert into state (status) values ('in progress');
insert into state (status) values ('not started');
insert into item (name, preority, user_id, category_id, state_id) values ('need help', '2', 2, 1, 1);
insert into comments (text, item_id) values ('I don.t see my comp', 1);
insert into attaches (path, item_id) values ('c:\img\1.jpg', 1);
insert into item (name, preority, user_id, category_id, state_id) values ('network don.t work', '5', 3, 2, 2);
insert into comments (text, item_id) values ('don.t open pornohub', 2);
insert into attaches (path, item_id) values ('c:\img\p.jpg', 2);
insert into item (name, preority, user_id, category_id, state_id) values ('we have a backups?', '10', 4, 3, 3);
insert into comments (text, item_id) values ('where are ours backups, man?', 3);
insert into attaches (path, item_id) values ('c:\img\b.jpg', 3);
select * from item_user;
select * from role;
select * from rules;
select * from rules_role;
select * from item;
select * from category;
select * from comments;
select * from attaches;
select * from state;

